### PR TITLE
Added fr_fr translation draft

### PR DESCRIPTION
**Pull request by storca**
Since I'm using this awesome software for a project, I added french translation for the user interface.

I translated what I could, there are still ~50 strings to verify or translate.

### CODE REVIEW

**Comment by alex-spataru** [comment]
Hi! Thanks a lot for the contribution! Just one minor request before merging, is it possible for you to create a `"Welcome_FR.txt"` file that translates the welcome/startup console messages? 

The welcome/startup messages are located in [`assets/messages`](https://github.com/Serial-Studio/Serial-Studio/tree/master/assets/messages) folder.

**Comment by storca** [comment]
I'll continue to translate the project, I'll also translate the Readme after UI and welcome text are done, but I'm quite busy 😅

**Comment by alex-spataru** [comment]
Thanks a lot! No rush at all! It'll be done when it's done, good luck with your work!

**Comment by storca** [comment]
The UI is mostly done, 2 strings are left to translate, every other string has an equivalent in french but might be innacurate, the french translations are up with fcb1681 (I ran lupdate).
Sorry about the multiple commits, I'm still learning...
Oops, I forgot to publish the translation...

**Comment by alex-spataru** [comment]
Thank you for the translations! Do you want me to merge the changes now, or shall I wait a little longer?

**Comment by storca** [comment]
I'll fix a typo, release the translation and I think it should be ok
I can't find the french language in the compiled asset above, did I forgot something ?

**Comment by alex-spataru** [comment]
Hi, sorry for the delay. These last three months where really busy for me (both with thesis & work-related stuff) and I am just getting a two-week break from everything. Can I do anything to help you with this PR?

**Comment by alex-spataru** [comment]
French translation added with the latest commits! If you are still interested, feel free to review it and fix anything that I might have missed 😄

**Pull request closed without merging**
