### PR TITLE
Doc suggestions

### PR DESCRIPTION
**Pull request by 2e0byo**
Hi!  I've just stumbled across this project. Like everyone else I've rolled my own (and it wasn't nearly as good).  I've made an aur package for archlinux users, so I took the liberty of editing the readme:
* to add the aur package
* to point out that serial-studio can recieve data over mqtt and tcp/udp

This latter is definitely a big attraction: I thought I was going to have to implement it myself.

I don't know what the policy is on things like this.  I'll remove the aur package if you intend to require compiling (though all it does is pull the sources and compile).

Looking forward to starting to use it!

### CODE REVIEW

**Comment by alex-spataru** [comment]
Thanks a lot for the contributions & interest in this project. Merging!

@DanielPrjct & @Foalyy: you might be interested in using this aur package, please let me know how it works for you in #15.

**Comment by alex-spataru** [comment]
@2e0byo Hi! I just transitioned Serial Studio to *Qt 6.2.0* with the latest commits. As of now, the `qtcharts` module is not longer required. However, the `qtserialport` module must be installed alongside Qt 6 in order to compile the application. Is it possible for you to update the [`serial-studio-git`](https://aur.archlinux.org/packages/serial-studio-git) package? I barely have used Arch Linux, my Linux experience is limited to Ubuntu-based distros :laughing:

**Comment by 2e0byo** [comment]
Done: thanks for letting me know :)

**Comment by alex-spataru** [comment]
Thanks a lot!

**Comment by alex-spataru** [comment]
@2e0byo Hi again! I just wanted to let you know that I needed to downgrade to Qt 5 again for 1.1.3/1.1.4, the Qt 6 version works, but the framework still has a lot of issues that can affect the performance & stability of Serial Studio.

In contrast to version [1.0.23](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v1.0.23), the latest version does not depend on the Qt Location & Positioning plugins. I am currently using a modified version of QMapControl because widgets are now generated directly with C++. 

Happy holidays and thanks a lot for the support!🎄

**Comment by 2e0byo** [comment]
Sorry this took a while: I've pushed up a new pkgbuild to the aur.   

Is the new tag `continuous` an intentional tip tag?  I currently extract the version with 

```bash
printf "%s" "$(git describe --long --tags | sed 's/\([^-]*-\)g/r\1/;s/-/./g;s/v//g')"
```
(Which can be found in the archwiki pages: I can read it, but my sed-fu isn't that good ;) ).  It makes sense (I think) for the aur package to be built against the latest code in master (suffix `-git` normally implies unstable on arch), but I suppose I could pin it to tagged releases.  At present it just works unless the deps change, though.

**Pull request merged**
